//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnumsNET.Analyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enums.NET.Analyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonGenericEnums members have moved to Enums.
        /// </summary>
        internal static string ENUMS001Description {
            get {
                return ResourceManager.GetString("ENUMS001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonGenericEnums members have moved to Enums.
        /// </summary>
        internal static string ENUMS001MessageFormat {
            get {
                return ResourceManager.GetString("ENUMS001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonGenericEnums Migrator.
        /// </summary>
        internal static string ENUMS001Title {
            get {
                return ResourceManager.GetString("ENUMS001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonGenericFlagEnums members have moved to FlagEnums.
        /// </summary>
        internal static string ENUMS002Description {
            get {
                return ResourceManager.GetString("ENUMS002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonGenericFlagEnums members have moved to FlagEnums.
        /// </summary>
        internal static string ENUMS002MessageFormat {
            get {
                return ResourceManager.GetString("ENUMS002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonGenericFlagEnums Migrator.
        /// </summary>
        internal static string ENUMS002Title {
            get {
                return ResourceManager.GetString("ENUMS002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnsafeEnums members have moved to Enums.
        /// </summary>
        internal static string ENUMS003Description {
            get {
                return ResourceManager.GetString("ENUMS003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnsafeEnums members have moved to Enums.
        /// </summary>
        internal static string ENUMS003MessageFormat {
            get {
                return ResourceManager.GetString("ENUMS003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnsafeEnums Migrator.
        /// </summary>
        internal static string ENUMS003Title {
            get {
                return ResourceManager.GetString("ENUMS003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnsafeFlagEnums members have moved to FlagEnums.
        /// </summary>
        internal static string ENUMS004Description {
            get {
                return ResourceManager.GetString("ENUMS004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnsafeFlagEnums members have moved to FlagEnums.
        /// </summary>
        internal static string ENUMS004MessageFormat {
            get {
                return ResourceManager.GetString("ENUMS004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnsafeFlagEnums Migrator.
        /// </summary>
        internal static string ENUMS004Title {
            get {
                return ResourceManager.GetString("ENUMS004Title", resourceCulture);
            }
        }
    }
}
