name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./Src
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./Src
    - name: Test .NET 4.8
      run: dotnet test -f net48 --no-restore --verbosity normal
      working-directory: ./Src
    - name: Test .NET 8
      run: dotnet test -f net8 --no-restore --verbosity normal
      working-directory: ./Src
